name: Publish package to GitHub Packages
on:
  release:
    types: [ created ]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Publish package to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
          SMMS_API_TOKEN: ${{ secrets.SMMS_API_TOKEN }}
          SMMS_USERNAME: ${{ secrets.SMMS_USERNAME }}
          SMMS_PASSWORD: ${{ secrets.SMMS_PASSWORD }}
        run: mvn --batch-mode deploy


      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

